name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Gives permission to push to gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # Keep '.' if index.html is in root
